### ISSUE TITLE
Octave 5.1.0 or 5.2.0

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#120]
Octave 5.1.0 is out. Bundle it up!

With this release we'll switch to non-versioned dependencies.

###  Blockers

* [x] #121 – netpbm download fails with SSL “issuer not trusted” error
* [x] #103 – Drop formula versioning
* [x] #96 – Version bumps affect indirect dependencies
* [x] #123 – libcerf is 404
* [x]  #76 – subversion build fails on macOS 10.12
* [x] #77 – build fails: rsvg-convert: command not found
* [x] #78 – octave build failed: crash during document generation stage
* [x] #79 – `test tar` is failing again
* [x] #81 – gdk-pixbuf installation fails on macOS 10.12
* [x] #83 – python@2 build fails on 10.12
* [X] #85 – octave 5.1.0 build fails in doc stage: 'Unknown token. Expected "QtHelpProject".'
* [ ] #110 – `pkg install -global` installs to user directory
* [x] #130 – Qt 5.11.2 build fails
* [x] #124 – Qt 5.12 will not build on OS X 10.11
* [x] #143 – Qt 5.12.5 build fails
* [x] #182 – Octave.app 5.1.0 build fails in doco generation step
* [x] #183 – Qt 5.13.2
* [x] #189 – 5.2.0 beta 1 still has 5.1.0 in symlink to binary
###  Maybes

* [x] #122 – Make versioned octave-app formulae keg-only
* [x] #42 - Try Qt 5.13
* [ ] #47 – Build against Qt 5.13.1 fails with QObject::moveToThread error in qcollectiongenerator 

###  Wishlist

* [x] #119 – Bundle JVM with Octave.app
* [x] #115  – Missing Retina 512@2x icon
* [x] #136 – Qt 5.11.3 build fails

**Comment by apjanke** [comment]
Oh, for Pete's sake. I can not get _any_ of the current Qt releases (5.11, 5.12, or 5.13) to build. (Well, 5.13 will build, but it throws a bad error when building Octave.) This might take a bit to sort out. Worst case, we can revert to one of the older patch versions that I was able to get to build.

Though I think we should try to get on to Qt 5.12 for Octave.app 5.1.0. Qt 5.12 is a Long Term Support release; 5.11 and 5.13 are not. I think we should be targeting LTS Qt releases for all our Octave.app releases, since Octave.app releases are themselves long-lived, and more concerned with stability than features.

**Comment by apjanke** [comment]
On the upside, I bought a new 10-core iMac Pro, so grinding through all these builds is a lot faster now...

**Comment by apjanke** [comment]
Okay, I've got a no-desktop (CLI front-end) build of Octave 5.1.0 out as beta 4: https://github.com/octave-app/octave-app/releases/tag/v5.1.0-beta4.

This one is still built against Qt, so it has Qt plotting enabled, but uses the Octave terminal CLI interface inside Terminal.app as its frontend. It works okay, but has some issues:

* The Octave CLI window is a window under the Terminal application, so you can't switch windows to it easily if you're doing other things in Terminal.
* There's a separate `octave-gui` process that shows up in the Dock
  * and it seems to keep on running after you exit the Terminal window used by the Octave CLI?
* Sometimes you get this when launching:
<img width="420" alt="Screen Shot 2019-11-03 at 10 28 17 PM" src="https://user-images.githubusercontent.com/2618447/68098715-5c5d3680-fe8c-11e9-8ec2-f9289f93bb24.png">

* Sometimes you get this when launching:
<img width="420" alt="Screen Shot 2019-11-03 at 10 29 35 PM" src="https://user-images.githubusercontent.com/2618447/68098719-62ebae00-fe8c-11e9-9fe8-c43d2f636173.png">

* It takes several seconds to launch, and there's no feedback from the macOS desktop UI to indicate that the launch is in progress.
* If you are typing in another window while the launch is happening, the newly-launched Terminal window can grab focus, and your typing can go there, possibly messing up the command line for launching Octave, so you get something that looks like this:
<img width="753" alt="Screen Shot 2019-11-03 at 10 52 48 PM" src="https://user-images.githubusercontent.com/2618447/68098772-b100b180-fe8c-11e9-9e20-989efb405add.png">

* Plots show up as windows under the `octave-gui` process/app, not Terminal, so you can't Cmd-backtick to cycle between them; you need to switch between applications.


Still, that's better than the desktop GUI just launching and hanging.

Maybe we could improve the launcher script by, instead of doing `tell application "Terminal"; activate; do script cmd; end tell`, which I think runs the Octave script inside a shell inside Terminal, we could tell Terminal to open up a new window and have it run `octave` as its application instead of a shell, after setting up the environment variables directly in AppleScript.

**Comment by apjanke** [comment]
Moved the Qt 5.11.x build failures to "wishlist" status since we got Qt 5.12 builds working, and Qt 5.12 is what we want to build and ship with anyway, since it's a LTS release. Only the older Octave 4.4.1 uses Qt 5.11.x now.

**Comment by apjanke** [comment]
Exciting news! I tried building Octave 5.1.0 against the new Qt 5.13 release, and it seems to improve the GUI freeziness problem!

I've rolled a 5.1.0 beta 5 built against Qt 5.13 here: https://github.com/octave-app/octave-app/releases/tag/v5.1.0-beta5. Please give it a try and let me know how it works for you.

**Comment by mpiqueca** [comment]
https://github.com/octave-app/octave-app/releases/tag/v5.1.0-beta5 report:

Testing on Mac mini (Mid 2011) High Sierra 10.13.6 (17G9016)

I tried as myself (mp), Admin, and as a Guest User.

In all cases, if I click first in the Command Window, which is showing a “>>” prompt, Octave hangs with spinning beach ball and must be Force-quit.

In all cases, if I click first in the File Browser sub window, I can then click in the Command Window and (as far as Ive tried: some “demo plot” and “sombrero” Octave works fine.  Since my personal config file starts Octave-gui without the File Browser sub window, this took me some time to figure out.

I almost always use the no-Gui Octave but wanted to get you this report (a bit delayed from November 5 but…)

Thanks for all you’re doing for us.

- Mike Pique
mobile +1.858.354.4391
The Scripps Research Institute, La Jolla, CA USA

**Comment by apjanke** [comment]
Well darn. Sebastian also reports freeziness. So much for that idea.

Thanks for the report!

I think at this point we should probably concentrate on making the CLI 5.1 Octave.app as nice as possible, and hope for a GUI fix in Octave 6.x.

**Comment by apjanke** [comment]
Octave 5.2.0 is out now. Let's skip 5.1.0 and just make a 5.2.0 release.

I'm continuing to work on an acceptable CLI front-end launching mechanism.

And Qt 5.14.1 is out now. This one might actually fix the freeziness! I've been running a 5.2.0 + Qt 5.14.1 build all day today with no freezes. But I'm not getting my hopes up yet.

https://github.com/octave-app/octave-app/releases/tag/v5.2.0-beta1

**Comment by rdzman** [comment]
In general, I rarely use the GUI, but in playing with 5.2.0 beta 1 on a 16" MacBook Pro running macOS Catalina 10.15.3, I've run into multiple freezes requiring a force quit. Also, sometimes the octave-gui menus in the menu bar are unresponsive even though the rest of the GUI is not frozen (command window works, no beach ball).

**Comment by apjanke** [comment]
Sebastian also reports freezes in 5.2.0 beta 1 on macOS Catalina.

Oh well. Back to working on a CLI front-end for 5.x.

**Comment by SinaKHezri** [comment]
hey guys it makes sense! i ran Octave 5.2.0 on Mac Os Catelina and as soon as clicked it froze and started Beachballing. But if you open the package contents and run the main script there it will be Fine

**Comment by apjanke** [comment]
What, really??? I have to try that; we might have a fix here!

**Comment by SinaKHezri** [comment]
Yes see of it works for you

**Comment by apjanke** [comment]
Exactly which "main script" were you running here? Can you tell me the path relative to the app bundle (i.e., underneath `/Applications/Octave-5.2.0.app`)?

**Comment by SinaKHezri** [comment]
under open package contents "Contents/Resources/Scripts/main.scpt" just run the script and it works!

**Comment by SinaKHezri** [comment]
> under open package contents "Contents/Resources/Scripts/main.scpt" just run the script and it works!
Just click on the Octave 5.2.0 icon in Applications then "show package contents" then the following

**Comment by apjanke** [comment]
Hot diggity! It works for me too on macOS 10.14.6!

This strongly suggests that it's something about our packaging and launcher scripts that is causing the problem.

One weird thing, though: When I build a vanilla Octave 5.x (like through a Homebrew formula) and run that, without any of the special Octave.app stuff, it hangs too. I wonder what's different about the Octave.app build?

**Comment by SinaKHezri** [comment]
Great news man.
Yeah i think there's something wrong with the launbcher too
Hmmm i should try that too see if it goes the same

**Comment by apjanke** [comment]
Sorry for the slow progress on this now that you've got a lead... we're in the middle of crunch time at my day job and it's probably gonna be a couple weeks before I can get to following this up.

**Comment by apjanke** [comment]
See https://github.com/octave-app/octave-app/issues/207 for a problem with running the Octave.app binaries from the command line. I think I'm going to work on fixing that.

**Comment by apjanke** [comment]
Well, this took long enough that it's superseded by https://github.com/octave-app/octave-app/issues/231 now. Making progress there, though! Looks like we might have an 8.x release out soon.

Closing as superseded.
