### ISSUE TITLE
2024-01 octapp-bundler nice-ification

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#257]
Some little things to make octapp-bundler nicer and easier to use.

For work on [#243 Octave 8.x and macOS 11+](https://github.com/octave-app/octave-app/issues/243).

## TODO

* [x] Figure out why a call on a fresh app build is exiting after the `brew install octave-octapp@x.y.z` stage.
  * Probably an errexit after `brew` returning nonzero?
* [ ] Do the build munging in a separate `./munging` dir, and then copy to `./build`, so the existence of the file there means it's all munged, and not in-progress?
* [ ] Put intermediate DMGs somewhere else too, so a DMG in `./build` means it's finished.
  * or maybe use `./build` for intermediates, and have a `dist/` or `target/` dir for finals.

Or maybe use `build/` for the intermediate things, and `dist/` or `build/dist/` for the final outputs. Or per-build-run subdirs for both.

**Comment by apjanke** [comment]
Renamed this from "2024-01 octapp-bundler nicification" to "2024-Q1 ..." because I'm not that ambitious, and obviously already missed that ETA.
