### ISSUE TITLE
Qt 6 support (for Octave 9.x)

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#262]
Sub-task for getting Octave 9 building with Qt6 for [the 9.0 builds](https://github.com/octave-app/octave-app/issues/243) and the [9.1 release](https://github.com/octave-app/octave-app/issues/270).

## TODO

* [x] Install qt6 octave-octapp again (w/ current deps) inside a regular Homebrew install and see if that works
  * (to see if it's a conflict between octapp Homebrew and system Homebrew, like I think the error message hints at)
* [x] Build a qt6 octapp 9.1 on a clean build box (no system Homebrew)
  * [x] Build clean macOS 12 and 14 Intel and AS build VMs
* [x] Fix my dotflies to handle no-brew machines, again

## References

* Related Octapp tickets
  * https://github.com/octave-app/octave-app/issues/274

Other references:

* Old core Homebrew attempt at this, w/ some stuff I haven't tried yet
  * https://github.com/Homebrew/homebrew-core/pull/141675
* Core Homebrew Qt 6.7 build fixes
  * Bug report: https://github.com/Homebrew/homebrew-core/issues/170616
  * PR for fix: https://github.com/Homebrew/homebrew-core/pull/170657
* Octave upstream posts
  * [RC for Octave 9.2.0](https://octave.discourse.group/t/release-candidate-for-octave-9-2-0-available/5579) post from Octave Discourse; 9.2.0 includes these Qt 6.7 fixes

**Comment by apjanke** [comment]
Last time I tried it like a week ago, my build of 9.1.0, done against Qt 6, failed during the build.

Might be due to incompatibility with Qt 6.7.0, which came out recently. There are new patches for it in the core octave formula.

* https://github.com/Homebrew/homebrew-core/issues/170616

TODO: Pull those in.

**Comment by apjanke** [comment]
fxcoudert [reports](https://github.com/Homebrew/homebrew-core/pull/170657#discussion_r1590640845) that the duplicate `:build` dep on libtool introduced by that core `octave` formula update was an oopsie. No actual need for a special `:build` dep, but I think I'll align my formulae with core just to reduce the diff output.

<img width="967" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/f9957d87-78c7-4c1f-ae60-ff9e15943d74">

**Comment by apjanke** [comment]
A couple weeks back, I [did a 9.1 build with the qt6 variant](https://github.com/octave-app/octave-app/issues/270#issuecomment-2071308224), and it just wouldn't launch. And then a few days later, I did it again, and the [build failed](https://github.com/octave-app/octave-app/issues/270#issuecomment-2095042574), maybe due to Qt 6.7 compatibility problems. I can't remember what the last state of it was. And there were GCC-related build problems with code 15.3 too. A new Xcode came out, and core Homebrew formula fixes for Qt 6.7; maybe things are fixed now.

Let's just do some more builds to establish a baseline as of 2024-05-24.

* [ ] build 9.1 qt6 in sys Homebrew on [ ] macOS 14 Intel [ ] macOS 14 AS
* [ ] build 9.1 qt6 as Octave.app on [ ] macOS 14 Intel [ ] macOS 14 AS
* [ ] try switching octave-octapp@9.1.0 dep to vanilla qscintilla2 instead of qscintilla2-octapp
* ...and then maybe on clean build machines

Current setup onn fortyhands (Intel macOS 14 VM, no system Homebrew), I've got it upgraded now, and uninstalled the system Homebrew:

```
Xcode 15.4
Build version 15F31d
Xcode CLT: 15.3.0.0.1.1708646388
Apple clang version 15.0.0 (clang-1500.3.9.4)
```

I'm doing the builds in system Homebrew on angharad and eilonwy first, for speed and convenience; that may give a positive result that the launch failure has disappeared, which would be nice.

...IN PROGRESS as of 2024-05-25 03:00...

**Comment by apjanke** [comment]
Now that the build against Qt 6.7.0 is fixed, I'm still getting the problem of builds using Qt6 failing to launch, with errors complaining about duplicate class definitions and maybe duplicate Qt 6 libs being loaded. Handling that in this other more-specific ticket:

* https://github.com/octave-app/octave-app/issues/274

**Comment by apjanke** [comment]
Well huh. I made some "clean" new macOS 12 build box VMs to do a Qt6 Octave.app 9.1 build in. And it still won't launch. On angharad, in VM "oabuild-2" (a fresh macOS 12 VM in VMware), after the build and installing the app from the resulting DMG, when I double-click the icon, I get a dialog asking if I want to rebuild the font cache, I click Yes, and then nothing. And from the command line:

```
janke@oabuild-2 ~ % /Applications/Octave-9.1.0_qt6preview.app/Contents/Resources/usr/bin/octave --gui
octave: GUI features missing or disabled in this build
janke@oabuild-2 ~ % /Applications/Octave-9.1.0_qt6preview.app/Contents/Resources/usr/bin/octave      
GNU Octave, version 9.1.0
Copyright (C) 1993-2024 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin21.6.0".

Home page:            https://octave.org
Support resources:    https://octave.org/support
Improve Octave:       https://octave.org/get-involved

For changes from previous versions, type 'news'.

octave:1> sombrero
error: no graphics toolkits are available!
error: called from
    figure at line 96 column 7
    newplot at line 120 column 10
    surf at line 77 column 9
    sombrero at line 68 column 5
octave:2> exit
janke@oabuild-2 ~ % 
```

Maybe this is a formula problem with the octapp qt6 9.1 formula/etc?

**Comment by apjanke** [comment]
Oh, a clue: Look at the ~/Library/Logs/Homebrew content after a "successful" build ot Octave-app with Qt 6 on my oabuild-as-2 VM.

<img width="451" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/672ce1f2-aeb7-4f63-85cf-8f1f1c16fae7">

There's no qt package there, nor several of the other packages, even though they're present in the app itself.

<img width="628" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/146a8f84-c6ed-48bd-bdd1-bb7688f6dc2e">

I bet that means they were poured from binary bottles instead of built from source. And I'm guessing that the qt 6 bottle, or some related bottles that use qt 6, is not actually relocatable, and has paths to the default /opt/homebrew prefix baked in to it. So the poured qt 6 bottle is not usable, the octave-app formula build doesn't recognize qt 6 as being present, and builds a no-gui app. That could also explain why my qt 5 build had so many more package download failures than my qt 6 build when they ran at the same time on the same hypervisor host on Saturday.

I think we need to force a build from source here.

The efficient way to do it would be to use the --build-from-source option on just packages which are known to need the explicit build-from-source and knon to be in the particular build we're doing. That'd take some logic and work, but would save the time of building packages which have relocatable bottles. OTOH, maybe there are additional formulae with bottles that aren't actually relocatble. Building them all from source could be the safest approach with respect to this issue.

The --build-from-source option only affects formulae listed explicitly on the `brew install` command line I think, not dependencies. Might need to do dependency calculation and explicit installation anyway.

**Comment by apjanke** [comment]
I added a mechanism to force building selected formulae, including qt 6, from source. https://github.com/octave-app/octave-app-bundler/commit/64c5c37f3676f4829e638416f41d9f3ebf63efcb

I'm only doing selected formulae, using a list of formulae I noticed might have spuriously-relocatable bottles, because building *everything* from source increases the build time a lot, and it's already a long slog. But might have to do that anyway, at least as an option, because I'm not sure which all formulae have spuriously-relocatable bottles, and identifying them one by one could take a long time, requiring many builds.

**Comment by apjanke** [comment]
When trying to build the next time, it failed an hour in on node.js, on VM oabuild-as.

<img width="1038" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/4be755c0-790f-4b7f-8a98-bc4c28e8b6f1">

But Finder says there's 18 GB left on the disk.

<img width="243" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/fadcfab2-ae23-44b1-b911-b589c15fba63">

Doesn't make a lot of sense to me. Surely the node.js build temporary dir doesn't get up to 18 GB big?

I rebooted and now it says there's 31 GB free.

<img width="248" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/b51e546d-02b9-4935-abaa-92bbe81f5560">

I don't understand how disk space works on modern macOS.

**Comment by apjanke** [comment]
During the vulkan-loader build, a few packages after the node build, it looks like it temporarily used almost 20 GB of disk space. df reported getting down to 11 GB free on the Data volume, and then bouncing back up to 29 GB free when it finished vulkan-loader and moved on to molten-vk.

<img width="783" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/43317b7b-e8ef-4fa0-a6a9-ebcb83eaf595">

(Or maybe I read the timing wrong, and that high size use was during node after all, and not the following few packages. That `while true; do echo ''; date; df -h; sleep 20; done` command requires manual watching and along with the `brew install` output, since there aren't timestamps in the brew output.)

TODO: Is there a program we can add to the pipeline that'll prepend every line of output with a timestamp? And set buffering on brew's stdout to work with that?

**Comment by apjanke** [comment]
Over on my Intel VM oabuild, doing a qt5 9.1 beta build (before some of my recent changes), it also failed with out of disk space while building node. I guess maybe node does take a lot of temporary space during the build, and there may be various ways the disk is filling up that I don't understand, maybe as a result of repeated builds or swap space or something.

<img width="1584" alt="image" src="https://github.com/octave-app/octave-app/assets/2618447/8272a66f-a64d-498d-b3ef-972127479d90">

Guess I'll just bump up the disk sizes on build boxes. In VMware I can expand existing disks, but with UTM that may mean starting over and rebuilding the VM from scratch, because AFAICT it can't expand disks. (Unless the underlying QEMU CLI tools can, but I'm not familiar with them at all.)

**Comment by apjanke** [comment]
Yeah. Testing looks good here, and I'm confident I identifed the core problem here. Closing this as Fixed.
