### ISSUE TITLE
Use `depends_on "texlive"` instead of manual-installed MacTeX?

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#297]
Following up on https://github.com/octave-app/octave-app/issues/293:

Should we switch to using a `depends_on "texlive" => :build` dependency instead of doing a hack to pull in a manually-installed (non-Homebrewed) MacTeX installation, for builds that require doco building?

Core Homebrew now has formulae for `texlive` and `mactex-no-gui` and other `mactex-*`, and is what they use now instead of a MacTeX requirement. Octapp's use of a non-brewed MacTeX and a custom `MacTeXRequirement` and custom bit to add it to the `$PATH` during the build is something of an anachronism, left over from how Homebrew did things like five years ago circa 2020.

Another approach would be to still use a TexLive installed on the system outside the Octave.app build (to avoid incurring the dependency and installation time), and install that with Homebrew, MacPorts, or something besides MacTeX, to get a system TeX installation but avoid the MacTeX Ghostscript installation. Probably avoid Homebrew so we can still run the Octave.app build on a "clean" system that doesn't have another Homebrew.

### Pros and cons

* Using `depends_on texlive` would make the installation automatic and scripted.
  * But would require _uninstalling_ texlive and its specific dependencies as part of the Octapp build process.
* `depends_on texlive` would incur a download and install, which are heavy.
  * But `brew`'s caching would prob take care of the download for repeated use on an existing VM, and the texlive install may be heavy but is nothing compared to a full build of Qt and other Octave dependencies in terms of compilation time.
* Non-brewed "system" MacTeX installs could be included in build-box images, for efficiency.
* `depends_on texlive` is what core Homebrew does now I think, and good to be aligned with them.
  * Nope, it isn't. As of 2025-01-18 and core Octave 9.3.0 formula, it has no dependency on `texlive`. Maybe they're not building all the docs?
* Using `brew install mactex` keeps a copy of the 6 GB `.pkg` file around after install?
  * https://www.reddit.com/r/LaTeX/comments/1e5nyrv/comment/ldndh28/
  * https://github.com/Homebrew/homebrew-cask/issues/62909

### Thoughts

It looks like the GUI-based MacTeX installer drops a ghostscript installation into /usr/local, which conflicts with the Homebrew-managed ghostscript? Maybe that's why I always have a ghostscript like that sitting around and bumping in to Homebrew. Avoiding that would be nice. ...Yeah, that looks like the case.

## References

* Discussions
  * ["Differences between texlive and mactex-no-gui"](https://www.reddit.com/r/LaTeX/comments/1e5nyrv/differences_between_texlive_and_mactexnogui/) on Reddit
* MacTeX doco
  * ["What is in the Package" page](https://www.tug.org/mactex/whatsinthepackage.html)
  * ["What is Installed" PDF](https://www.tug.org/mactex/What_Is_Installed.pdf)
  * [More Packages](https://tug.org/mactex/morepackages.html), including BasicTeX
  * [FAQ 4: MacTeX and Homebrew](https://tug.org/mactex/faq.html#qm04)
    * Says to put `/Library/TeX/texbin` on the front of your path to pick up MacTeX-installed commands.
* Tools
  * [Third-party MacTeX Ghostscript uninstaller](https://gist.github.com/gwerbin/dcba755b0484423e9e45)

## TODO

* [x] Benchmark download and install of `texlive` and `mactex*` Homebrew formulae.
  * [x] Check sizes, too: brew cask installation holds on to the whole package file?
* [x] Learn about the differences between the `texlive` and `mactex*` formulae. And how Homebrew is handling TeX in general these days.
* [x] Test MacTeX and other variants for /usr/local ghostscript installation behavior.

## Conclusion

2025-02-16: Decided to stick with MacTeX, use BasicTeX to save time and disk space, and not add texlive dependencies or anything like that. Will add ability to import TeX from a system Homebrew install if I ever start installing it that way.

**Comment by apjanke** [comment]
Decided to stick with pulling in TeX from MacTeX installs, use BasicTeX to save time and disk space, and not add a `texlive` dependency or automatic installs or anything like that.

Going to keep considering TeX to be an external tool that is part of the build environment you need to set up on a machine you're building Octave.app on. Adding a `texlive` dependency to the octapp octave formulae will complicate them and the `bundle_octave_app` tool, maybe add a lot of extra time to builds, and reduce flexibility in how you can install TeX, and cause potential conflicts with other Homebrewed stuff.

The BasicTeX package seems to work fine for building Octave's doco, and it's only 350 MB instead of 11 GB for the full MacTeX installation. Installing it is no biggie. And it can be picked up in formulae the same way that MacTeX can, so no code changes are needed.

```
[texlive] $ pwd
/usr/local/texlive
[texlive] $ du -sh *
 11G	2024
374M	2024basic
4.0K	texmf-local
```

If I or other Octave.app devs end up wanting to install TeX on their build systems using `brew`, then I can modify the octave formulae in homebrew-octave-app to detect and import it from the Homebrew installation location as well as the MacTeX install location. Not doing that now, because I don't plan on using this installation mechanism for now.

### Other notes

You can skip the installation of Ghostscript in MacTeX's installation by unchecking Ghostscript in the customization screen in the installer wizard. And Homebrew's `mactex` and `basictex` cask formulae do this programmatically. So this "MacTeX messes up my /usr/local with a non-brewed ghostscript" conflict is avoidable.

After some detailed examination, that Ghostscript installation looks like the only conflict or clutter caused by MacTeX. So now I don't mind installing MacTeX.

I made a little mactex-cleaner tool in https://github.com/apjanke/misc-tools-apj that can remove the Ghostscript installed by MacTeX to clean up a Homebrew-managed /usr/local.

### Resolution

Closing this as WontDo.
