### ISSUE TITLE
Octave.app 9.3 release

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#300]
Octave [9.3.0 is out](https://octave.org/news/release/2024/12/15/octave-9.3.0-released.html). Time for an Octave.app release of it.

Milestone:

* https://github.com/octave-app/octave-app/milestone/19

## Blockers

* https://github.com/octave-app/octave-app/issues/299
* https://github.com/octave-app/octave-app/issues/302
* https://github.com/octave-app/octave-app/issues/310
* https://github.com/octave-app/octave-app/issues/311

## TODO

* [ ] Make mercurial a build-only dependency instead of a normal dependency?
  * And find out why it isn't getting automatically installed for `brew install --HEAD octave-stable`!
    * I think bc in `brew install`, all files are fetched before installing any of the deps, so the "fetch octave" happens before the mecurial dep actually gets installed?
* [x] Say "+ Octave.app patches" instead of just "+ patches" in our customized `ver` output?
* [ ] Have formulae remove versioned symlinks as part of uninstall?
  * Doesn't look possible. There's no "pre-uninstall" hook in `brew`?

**Comment by apjanke** [comment]
Hmm. Got this build failure when trying to do a 9.3. An automatic brew cleanup broken by some intervention we did?

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/a0d21da5-e0da-46bc-b31f-64e395c9562a" />

Handling under separate ticket: https://github.com/octave-app/octave-app/issues/311

**Comment by apjanke** [comment]
Sigh. Qt breakage again. GUI app won't launch; nothing pops up when I double click it. When running from command line, I get this.

```
[usr] $ pwd
/Applications/Octave-9.3.app/Contents/Resources/usr
[usr] $ ./bin/octave
objc[97117]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x1062e8710) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x10ad98710). One of the two will be used. Which one is undefined.
objc[97117]: Class KeyValueObserver is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x1062e8738) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x10ad98738). One of the two will be used. Which one is undefined.
objc[97117]: Class WeakPointerLifetimeTracker is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x1062e8788) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x10ad98788). One of the two will be used. Which one is undefined.
objc[97117]: Class RunLoopModeTracker is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x1062e87d8) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x10ad987d8). One of the two will be used. Which one is undefined.
objc[97117]: Class QDarwinPermissionHandler is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x1062e8850) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtCore.framework/Versions/A/QtCore (0x10ad98850). One of the two will be used. Which one is undefined.
objc[97117]: Class QMetalLayer is implemented in both /Applications/Octave-9.3.app/Contents/Resources/usr/Cellar/qt/6.8.2/lib/QtGui.framework/Versions/A/QtGui (0x108b64b08) and /opt/homebrew/Cellar/qt/6.8.2/lib/QtGui.framework/Versions/A/QtGui (0x10a718b08). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x60000309c170) is not the object's thread (0x60000309c630).
Cannot move to target thread (0x60000309c170)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, minimal, cocoa.

Abort trap: 6
[usr] $
```
